{{- if or .Values.containers .Values.initContainers -}}

{{- if .Values.containers }}
{{- range .Values.containers }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "component.labels" $ | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
      {{- if (contains "sha256:" .tag) }}
    - name: {{ trimPrefix "sha256:" .tag  | quote }}
      {{- else }}
    - name: {{ .tag | quote }}
      {{- end }}
      from:
        kind: DockerImage
        {{- if (contains "sha256:" .tag) }}
        name: '{{ tpl .registry $ }}/{{ tpl .repository $ }}/{{ .image }}@{{ .tag }}'
        {{- else }}
        name: '{{ tpl .registry $ }}/{{ tpl .repository $ }}/{{ .image }}:{{ .tag }}'
        {{- end }}
      referencePolicy:
        type: Local
{{- end }}
{{- end }}
{{- if .Values.initContainers }}
{{- range .Values.initContainers }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "component.labels" $ | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
      {{- if (contains "sha256:" .tag) }}
    - name: {{ trimPrefix "sha256:" .tag  | quote }}
      {{- else }}
    - name: {{ .tag | quote }}
      {{- end }}
      from:
        kind: DockerImage
        {{- if (contains "sha256:" .tag) }}
        name: '{{ tpl .registry $ }}/{{ tpl .repository $ }}/{{ .image }}@{{ .tag }}'
        {{- else }}
        name: '{{ tpl .registry $ }}/{{ tpl .repository $ }}/{{ .image }}:{{ .tag }}'
        {{- end }}
      referencePolicy:
        type: Local
{{- end }}
{{- end }}
{{- end }}
