{{- if or .Values.containers .Values.initContainers -}}

{{- if .Values.containers }}
{{- range .Values.containers }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "component.labels" $ | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: {{ .tag | quote }}
      from:
        kind: DockerImage
        name: '{{ tpl .registry $ }}/{{ tpl .repository $ }}/{{ .image }}:{{ .tag }}'
      referencePolicy:
        type: Local
{{- end }}
{{- end }}
{{- if .Values.initContainers }}
{{- range .Values.initContainers }}
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: {{ $.Release.Name }}-{{ .name }}
  labels:
    {{- include "component.labels" $ | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
    - name: {{ .tag | quote }}
      from:
        kind: DockerImage
        name: '{{ tpl .registry $ }}/{{ tpl .repository $ }}/{{ .image }}:{{ .tag }}'
      referencePolicy:
        type: Local
{{- end }}
{{- end }}
{{- end }}
