{{- if and .Values.route .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{- include "component.labels" . | nindent 4 }}
  name: {{ include "component.fullname" . }}
spec:
  host: {{tpl  .Values.route.host $ | quote}} # the value of host is set in values.yaml
  port:
    targetPort: {{ .Values.route.targetPort }} # this is the port name your service listens on
  to:
    kind: Service
    name: {{ include "component.fullname" . }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
