{{- if and .Values.service .Values.service.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "component.fullname" . }}
  labels:
    {{- include "component.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }} 
  selector:
    {{- include "component.selectorLabels" . | nindent 4 }}
{{- end }}
