name: On Pull Request to Main
on:
  pull_request:
    branches:
      - main
jobs:
  validate-changes:
    if: '!github.event.pull_request.head.repo.fork'
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        include:
          - repo_name: quickstart-openshift
            params: --set-string global.secrets.databasePassword=test --set-string global.secrets.databaseUser=test --set-string global.secrets.databasePassword=databaseName
          - repo_name: pubcode
            params: ''
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./helm-service
      - uses: actions/checkout@v4
        with:
          repository: bcgov/${{ matrix.repo_name }}
          ref: main
          path: ./${{ matrix.repo_name }}
      - name: Add Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: |
          cd ./helm-service/util
          npm ci
      - name: Execute Program
        run: |
          DESTINATION_REPO=${{ matrix.repo_name }}  node ./helm-service/util/index.js
      - name: Validate Changes
        shell: bash
        run: |
          cd ./${{ matrix.repo_name }}/charts/${{ matrix.repo_name }}
          helm dependency update
          helm template ${{ matrix.repo_name }} --debug ${{ matrix.params }} .
          
