name: On Pull Request to Main
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - labeled
      - unlabeled
      - edited
    branches:
      - main
jobs:
  validate-changes:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        repo_names: [quickstart-openshift, pubcode]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: bcgov/${{ matrix.repo_names }}
          ref: main
          path: ./../${{ matrix.repo_names }}
      - name: Validate Changes
        shell: bash
        run: |
          #recursively print directories and contents
          tree 
